version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: pd-chat
      POSTGRES_USER: pd-chat-user
      POSTGRES_PASSWORD: pd_pass_1
    volumes:
      - pgdata2:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pgdata2: