version: '3.8'

services:
  vector_db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: pd-chat
      POSTGRES_USER: pd-chat-user
      POSTGRES_PASSWORD: pd_pass_1
    volumes:
      - pgdata2:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  chat_db:
    image: mongo
    volumes:
      - ./data-node:/data/db
    ports:
      - "27018:27017"

volumes:
  pgdata2: