create table "public"."questions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "question" text
);


alter table "public"."questions" enable row level security;

CREATE UNIQUE INDEX questions_pkey ON public.questions USING btree (id);

alter table "public"."questions" add constraint "questions_pkey" PRIMARY KEY using index "questions_pkey";


